### PR TITLE
Added methods for use in autoLayout against column views technique

### PR DESCRIPTION
**Pull request by caoimghgin**
Methods will align leading and trailing edges against one or more
views. For use in an autoLayout defined by UIView columns technique.

//
// Example code
//
- (void)updateConstraints
  {
  [super updateConstraints];
  
  NSString *visualFormat = @"H:|-[col1(<=1000)]-[col2(==col1)]-[col3(==col1)]-[col4(==col1)]-[col5(==col1)]-[col6(==col1)]-|";
  NSDictionary *metrics = nil;
  NSDictionary *views = @{@"col1":self.col1, @"col2":self.col2, @"col3":self.col3, @"col4":self.col4, @"col5":self.col5, @"col6":self.col6};
  [self addConstraints: [NSLayoutConstraint constraintsWithVisualFormat:visualFormat  options:NSLayoutFormatAlignAllTop metrics:metrics views:views]];
  
  CGFloat rowHeight = 44.0f;
  CGFloat rowGutter = 10.0f;
  CGFloat topInset = 100.0f;
  
  // Row 1
  [self.lastName autoPinEdge:ALEdgeTop toEdge:ALEdgeTop ofView:self withOffset:topInset relation:NSLayoutRelationEqual];
  [self.lastName autoPinLeadingEdgeToView:self.col1 andTrailingEdgeToView:self.col2 forHeight:rowHeight];
  
  [self.firstName autoPinEdge:ALEdgeTop toEdge:ALEdgeTop ofView:self withOffset:topInset relation:NSLayoutRelationEqual];
  [self.firstName autoPinLeadingEdgeToView:self.col3 andTrailingEdgeToView:self.col4 forHeight:rowHeight];
  
  [self.middleName autoPinEdge:ALEdgeTop toEdge:ALEdgeTop ofView:self withOffset:topInset relation:NSLayoutRelationEqual];
  [self.middleName autoPinLeadingEdgeToView:self.col5 andTrailingEdgeToView:self.col6 forHeight:rowHeight];

}

### CODE REVIEW

**Comment by smileyborg** [comment]
I'm not sure I fully understand the use case for this here.

The new code looks good. However, it doesn't look to be substantially different than the other existing API methods which the methods call internally. Even if this use case is generally applicable to more people, it looks like we're only saving 1 line of code here for each API call.

This is the hardest part about designing an API like this: deciding when to draw the line between increasing the complexity/size of the API with new methods, and keeping it simple at the cost of some reduced functionality. For these particular methods, I'm leaning towards the latter.

What do you think?

**Comment by caoimghgin** [comment]
I think being conservative with pulls is a very good idea!

With that in mind, I'd suggest the following...

I remove from the .h file the following method...

autoPinLeadingEdgeToView:leadingPeerView
andTrailingEdgeToView:trailingPeerView;

and keep the following method exposed....

autoPinLeadingEdgeToView:leadingPeerView
andTrailingEdgeToView:trailingPeerView forHeight:height

That way, we have a method which neatens up everything into a two line
call. In this particular use case (which I'll show in a moment).

// With New Method

```
 [self.lastNameTextField autoPinEdge:ALEdgeTop toEdge:ALEdgeTop ofView:
```

self withOffset:topInset relation:NSLayoutRelationEqual];

```
 [self.lastNameTextField autoPinLeadingEdgeToView:self.col1
```

andTrailingEdgeToView:self.col2 forHeight:rowHeight];

// Curent release methods

```
[self.lastNameTextField autoPinEdge:ALEdgeTop toEdge:ALEdgeTop ofView:
```

self withOffset:topInset relation:NSLayoutRelationEqual];

```
[self.lastNameTextField autoPinEdge:ALEdgeLeading toEdge:ALEdgeLeading
```

ofView:self.col1];

```
[self.lastNameTextField autoPinEdge:ALEdgeTrailing toEdge:ALEdgeTrailing
```

ofView:self.col2];

```
[self.lastNameTextField autoSetDimension:ALDimensionHeight toSize:44.0f
```

];

This _may_ be a situation where many users simply would not use the
autoLayout columns technique, which is something I've been working with for
a while now. The general idea is that newspapers and magazines have worked
very well using well defined column grid to lay out information in a
visually pleasing way. I'm finding it's working well for mobile devices too.

For a fuller use case scenario, this project attached would be helpful.
It's an experiment in creating greater separation between the View and
Controller when programmatically creating layouts. (We are told to follow
the MVC Pattern, yet the viewController is mushed together pretty tightly
by design).

The RJView is an example of creating a form a user may fill out where we'd
like to give the full rotation capabilities, possibly breaking and
recreating constraints upon rotation.

Anyway, let me know what you think.

**Comment by caoimghgin** [comment]
https://github.com/caoimghgin/ModelViewControllerStudy

**Comment by caoimghgin** [comment]
You know something. Let me think on this for a day. It's useful, but I
don't think it's named properly. I'll come up with something!

**Comment by smileyborg** [comment]
Have you had any thoughts on this? (I've been busy recently and haven't had much time to work on anything myself...)

The one thing that did come to mind is that this might make a really nice category of its own. Think of it as extensions to these helper methods, almost like a category on the category. This way, it would be completely independent so people who want to have additional API methods (perhaps with more raw power, etc) can just import the extra header for this new category, which internally wraps some calls to the existing API of this UIView+AutoLayout category. But for people who don't need or aren't doing these sort of things can stick with the basic core methods alone.

What do you think?

**Comment by caoimghgin** [comment]
You know, I actually did do some work on this, but haven’t had the time to push it up to you. 

I think the extension category is a fine idea! Something like UIView+AutoLayoutForColumns

I’ll mock it up see how it looks!

**Comment by caoimghgin** [comment]
Hey Tyler,

Finally got around to trying to extend the UIView+AutoLayout category and I suppose I wasn't finding much happiness...

First, I was simply going to pop in my two new methods in a new category named UIView+AutoLayoutForColumns. However, to make that work, it would require a copy/paste of three private methods inside UIView+AutoLayout.m, which didn’t seem like the nicest solution.

Next, I thought I’d get fancy and create a category on the category itself! No happiness there either (the + sign will degrade into a _ when creating the category extension, otherwise, I’d think it would work fine).

Thirdly, I could simply rename the UIView+AutoLayout category to UIView+AutoLayoutForColumns, and then publish that as a pod from my own gitHub account but the additional feature, IMHO, doesn’t really deserve a whole new repo. 

I’ll remove the current pull request and upload a cleaner (more useful?) class and see if that looks good enough to pull in. However, if you have other ideas on how I might elegantly extend the category (which sounds like a fine idea) I’m all ears.

PS - Lately, I’m using CocoaPods as repo for all things third party. Otherwise, I’d happily import and modify UIView+AutoLayout at will. Besides. I’d LOVE to have contributed something to a nice library. ;-)

**Comment by smileyborg** [comment]
I don't think copy-pasting some of the internal methods is that terrible if the idea is that this new category/pod would be used instead of the UIView+AutoLayout one, but I agree if both will exist it's not so great.

What I would recommend is that we refactor the current project a bit so that all of the internal private methods (prefixed by `al_`) are exposed in a separate header file. So what that would look like:

_Public API_

```
// UIView+AutoLayout.h

@interface UIView (AutoLayout)

- (NSArray *)autoCenterInSuperview;

// ...etc

@end 
```

_Private internal methods_

```
// UIView+AutoLayoutInternal.h

@interface UIView (AutoLayoutInternal)

- (UIView *)al_commonSuperviewOfViews;

// ...etc

@end 
```

If done this way, you could then `#import UIView+AutoLayoutInternal.h` at the top of your category and gain access to all the private methods. Regular users would continue to just `#import UIView+AutoLayout.h` which would only expose the public API methods.

How's that sound?

**Comment by caoimghgin** [comment]
Hmmmm….

I’m not sure making the internal methods public would be so good. I like internal methods. Keeps things clean.

Well, maybe check out the latest commit I did this morning. I added a ExampleConstraintDemo8

If that doesn’t convince, nothing will ;-)

**Comment by smileyborg** [comment]
The internal methods would not be made public, they would just be available to import into other .m files (such as yours that are effectively extensions on the category).

Since users would never import this private header, they would continue to not see these private methods at all.

This is the same design pattern recommended in Objective-C when you have a superclass with private methods that you only want to expose to subclasses.

**Comment by caoimghgin** [comment]
Well, in that case. I like! I’ll have to circle back to this. Work must be done.

**Comment by smileyborg** [comment]
No rush. Do you want to take a stab at refactoring this or would you like me to work on it when I get some time?

**Comment by caoimghgin** [comment]
I’d love to, so long as no rush.

**Comment by smileyborg** [comment]
@caoimghgin I've been working on unit tests for this library recently, and I actually had a need to do effectively what we were discussing here. Take a look at the [UIView+AutoLayoutInternal.h file](https://github.com/smileyborg/UIView-AutoLayout/blob/master/Tests/AutoLayoutTests/UIView%2BAutoLayoutInternal.h).

You can probably take this file and more or less move it into the main repo source to accomplish what we were talking about. Let's just make sure to also add some more comments at the top warning regular users not to import this header of private/internal methods, since it will now be included in the source files they download.

**Comment by caoimghgin** [comment]
Ahhh! Nice! I'll implement ASAP.

**Comment by caoimghgin** [comment]
Oh, that is nice! Just implimented. Say, if I intended to cocoaPod UIView+AutoLayoutColumns (private/public... not sure) I'd bet I would add UIView+AutoLayout as a dependency and let the manager handle the install of your pod. (I am playing catch-up with pods so looking forward to making one of my own). Anyway, I'm wondering if I should include UIView+AutoLayoutInternal.h in my pod or do you think you'll distro  UIView+AutoLayoutInternal.h within next version of UIView+AutoLayout?

**Comment by smileyborg** [comment]
Yes, CocoaPods definitely supports dependencies like this (haven't used them myself though). The idea is that `UIView+AutoLayoutInternal.h` would be part of this UIView+AutoLayout pod though, to allow other downstream libraries like yours to work on top of it, and to facilitate the unit tests as it currently does. That's why we need some big warnings to users not to import that header.

**Comment by caoimghgin** [comment]
Brilliant. Yes. When you're satisfied with UIView+AutoLayoutInternal, bundle it up with your pod. Let me know there is an update, and I'll put out a pod which links up! I think we can close out this pull request ;-)

**Comment by smileyborg** [comment]
OK. I'm planning on waiting to release the next version until after the unit test suite is complete with near 100% code coverage. I'm trying to tackle a chunk each day, so hopefully it will be done within a week or so. If you want to work on any of this stuff sooner, just use the existing `UIView+AutoLayoutInternal.h` file locally alongside the current pod.

**Comment by smileyborg** [comment]
Sorry this took so long to follow up on! But great news:
1. UIView+AutoLayout is now deprecated, because there's a brand new replacement: [PureLayout](https://github.com/smileyborg/PureLayout)! The main enhancement that PureLayout adds is full OS X support, with almost the entire codebase shared.
2. As part of PureLayout, I've exposed the private internal methods in a header file that is included with the Cocoapod source ([PureLayout+Internal.h](https://github.com/smileyborg/PureLayout/blob/master/Source/PureLayout%2BInternal.h)). That means that you (and anyone else) who wants to build a dependent library can do so knowing that all the internal methods and functionality is available.

Let me know what you think!

**Pull request closed without merging**
